[tool.poetry]
name = "attestation-proxy"
version = "0.3.2"
description = "Dual-port attestation proxy for sek8s"
authors = ["Kyle Widmann <kyle@chutes.ai>"]
readme = "README.md"
packages = [{include = "attestation_proxy"}]

[tool.poetry.dependencies]
python = ">=3.12,<3.15"
sek8s-common = {path = "../sek8s-common", develop = true}
cryptography = "^45.0"
httpx = "^0.28.1"
backoff = "^2.2.1"
loguru = "^0.7.3"

[tool.poetry.scripts]
attestation-proxy = 'attestation_proxy.service:run'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
