---
- name: Security hardening
  tags: security
  block:
    - name: Chroot and init hardening
      ansible.builtin.include_tasks: chroot-hardening.yml
      tags:
        - chroot-hardening
        - init-hardening

    - name: Disable cloud-init
      ansible.builtin.include_tasks: disable-cloud-init.yml
      tags:
        - chroot-hardening
        - init-hardening