ARG BUSYBOX_VERSION=1.37
FROM busybox:${BUSYBOX_VERSION} AS base

##################################################
## PRODUCTION ##
##################################################

FROM base AS production

##################################################
## DEVELOPMENT ##
##################################################

FROM base AS development
