[tool.poetry]
name = "sek8s-workspace"
version = "0.0.0"
description = "Meta workspace for sek8s packages"
authors = ["Kyle Widmann <kyle@chutes.ai>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<3.15"
sek8s = {path = "src/sek8s", develop = true}
sek8s-common = {path = "src/sek8s-common", develop = true}
attestation-proxy = {path = "src/attestation-proxy", develop = true}
chutes-cvm = {path = "src/chutes-cvm", develop = true}

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
openapi-spec-validator = "^0.6.0"
pytest-cov = "^7.0.0"
bandit = "^1.7.8"
flake8 = "^7.0.0"
black = "^24.3.0"
isort = "^5.13.2"
mypy = "^1.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
norecursedirs = ["tests/security"]
asyncio_mode = "strict"

[tool.isort]
profile = "black"

[tool.coverage.report]
exclude_also = [
    "def __repr__",
    "if self\\.debug",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "@(abc\\.)?abstractmethod",
]
omit = [
]

[tool.mypy]
ignore_missing_imports = false

[[tool.mypy.overrides]]
module = [
    "pynvml",
    "substrateinterface",
    "aiocache",
    "bittensor_wallet",
    "yaml",
]
ignore_missing_imports = true
