"""Standalone host CPU performance tuning for TDX VMs.

Applies the host-OS power settings NVIDIA recommends for Confidential Computing
("Setting Up the Host OS" in the NVIDIA CC Deployment Guide DU-12302-001):

    CPU frequency governor -> performance
    CPU C-states C1E, C6   -> disabled

Deliberately *not* tied to the VM lifecycle: an operator runs ``apply`` to tune
the host and ``restore`` to revert. ``apply`` snapshots the pre-tuning values to
RESTORE_SCRIPT so the original state can be restored later. Shallow idle states
(POLL, C1) are left enabled per NVIDIA guidance, which preserves thermal
headroom; only the deep states (C1E, C6) that hurt latency are disabled. This
has no effect on TDX measurements.

Usage:
    python -m chutes_cvm.host.tune apply
    python -m chutes_cvm.host.tune restore
"""

from __future__ import annotations

import argparse
import glob
import os
import sys

from chutes_cvm import proc

# Written by apply_tuning(); consumed by restore_tuning(). Stored under
# /var/lib/chutes/ so it survives /tmp cleanups while the VM is running.
RESTORE_SCRIPT = "/var/lib/chutes/tdx-host-tuning-restore.sh"

# NVIDIA recommends disabling only these C-states by name (not POLL/C1).
DISABLE_CSTATES = ("C1E", "C6")


def _read(path: str) -> str | None:
    try:
        with open(path) as f:
            return f.read().strip()
    except OSError:
        return None


def _write_root(path: str, value: str) -> None:
    if os.geteuid() == 0:
        with open(path, "w") as f:
            f.write(value)
        return
    proc.run(
        ["sudo", "tee", path],
        input=value,
        text=True,
        stdout=proc.DEVNULL,
        stderr=proc.DEVNULL,
        check=False,
    )


def apply_tuning() -> None:
    """Snapshot current settings, then apply NVIDIA-recommended host tuning.

    If a restore script already exists the host is already tuned: settings are
    reapplied without re-snapshotting, so the original saved state is preserved.
    """
    already_tuned = os.path.isfile(RESTORE_SCRIPT)
    if already_tuned:
        print(
            f"Host already tuned (restore script at {RESTORE_SCRIPT}); reapplying settings only."
        )

    restore_cmds: list[str] = [
        "#!/usr/bin/env bash",
        "# Restore host CPU settings captured before TDX host tuning.",
        "# Generated by chutes_cvm.host.tune apply -- do not edit.",
        "",
    ]

    print("CPU frequency governor -> performance")
    for gov_file in sorted(
        glob.glob("/sys/devices/system/cpu/cpu*/cpufreq/scaling_governor")
    ):
        if not already_tuned:
            saved = _read(gov_file)
            if saved is not None:
                restore_cmds.append(f"echo {saved} | sudo tee {gov_file} > /dev/null")
        _write_root(gov_file, "performance")

    print(f"C-states {', '.join(DISABLE_CSTATES)} -> disabled (POLL/C1 left enabled)")
    for state_dir in sorted(glob.glob("/sys/devices/system/cpu/cpu*/cpuidle/state*")):
        name = _read(os.path.join(state_dir, "name"))
        if name not in DISABLE_CSTATES:
            continue
        disable_file = os.path.join(state_dir, "disable")
        if not already_tuned:
            saved = _read(disable_file)
            if saved is not None:
                restore_cmds.append(
                    f"echo {saved} | sudo tee {disable_file} > /dev/null"
                )
        _write_root(disable_file, "1")

    if not already_tuned:
        restore_cmds += [
            "",
            "echo 'Host CPU settings restored.'",
            f"rm -f {RESTORE_SCRIPT}",
        ]
        try:
            os.makedirs(os.path.dirname(RESTORE_SCRIPT), exist_ok=True)
            with open(RESTORE_SCRIPT, "w") as f:
                f.write("\n".join(restore_cmds) + "\n")
            os.chmod(RESTORE_SCRIPT, 0o755)  # nosec B103
            print(f"Restore snapshot written to {RESTORE_SCRIPT}")
        except OSError as exc:
            print(f"Warning: could not write restore script: {exc}")

    print("\nHost tuning applied. Revert with:")
    print("    chutes-cvm host restore   (or: python -m chutes_cvm.host.tune restore)")


def restore_tuning() -> None:
    """Run the restore script emitted by apply_tuning(), if present."""
    if not os.path.isfile(RESTORE_SCRIPT):
        print("Nothing to restore: no tuning snapshot found.")
        return
    print("Restoring host CPU settings...")
    result = proc.run([RESTORE_SCRIPT], check=False)
    if result.returncode != 0:
        print(f"Warning: restore script exited {result.returncode}")


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="python -m chutes_cvm.host.tune",
        description="Apply or restore NVIDIA-recommended host CPU tuning for TDX VMs.",
    )
    sub = parser.add_subparsers(dest="action", required=True)
    sub.add_parser("apply", help="Snapshot current settings, then apply host tuning.")
    sub.add_parser("restore", help="Restore settings saved by a prior apply.")
    args = parser.parse_args()

    if args.action == "apply":
        apply_tuning()
    else:
        restore_tuning()
    return 0


if __name__ == "__main__":
    sys.exit(main())
