class AttestationException(Exception): ...


class TdxQuoteException(AttestationException): ...


class NvTrustException(AttestationException): ...


class NvmlException(AttestationException): ...


class NonceError(AttestationException): ...
